# Generated by Django 4.1 on 2022-08-22 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 13, 30, 35, 64115, tzinfo=datetime.timezone.utc)),
        ),
    ]
