# Generated by Django 4.1 on 2022-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article__date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
