# Generated by Django 4.1 on 2022-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='Nice article', max_length=140),
            preserve_default=False,
        ),
    ]
